### ISSUE TITLE
non default payable

### ISSUE THREAD

**Issue by ajunge** [cclp-project/cclp-contracts#15]
So if someone by mistake sends ETH to our contract it will be rejected

**Comment by Vulturio** [comment]
What about this? from Solidity 0.5 : https://solidity.readthedocs.io/en/v0.5.0/contracts.html

> Furthermore, this function is executed whenever the contract receives plain Ether (without data). Additionally, in order to receive Ether, the fallback function must be marked payable. If no such function exists, the contract cannot receive Ether through regular transactions.

By the way, I make the clasic non payable fallback and test here; https://github.com/UncleVultur/cclp-contracts/tree/fallback

**Comment by ajunge** [comment]
Makes. Sense. Did you add it to any PR?

**Comment by Vulturio** [comment]
> Makes. Sense. Did you add it to any PR?

Yes, to this https://github.com/cclp-project/cclp-contracts/pull/18
