### ISSUE TITLE
Blacklist

### ISSUE THREAD

**Issue by ajunge** [cclp-project/cclp-contracts#5]
Some address need to be blacklisted. They cannot execute transfer is they are on the blancklist.
A blacklist owner adds and removes ppl from the blacklist

**Comment by joadr** [comment]
I cannot edit the asignee, but I would like to do this one

**Comment by ajunge** [comment]
@joadr check this one: https://github.com/centrehq/centre-tokens/blob/master/contracts/Blacklistable.sol
